services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: estoque_db
      POSTGRES_USER: glee
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: