
services:
  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: estoque_db
      POSTGRES_USER: glee
      POSTGRES_PASSWORD: 12345

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: estoque_db
      POSTGRES_USER: glee
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/estoque_db
      SPRING_DATASOURCE_USERNAME: glee
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - postgres

volumes:
  pgdata: